"""empty message

Revision ID: 4a03c37cc44f
Revises: ace59cb8ed7b
Create Date: 2022-06-16 17:27:06.101440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a03c37cc44f'
down_revision = 'ace59cb8ed7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=40), nullable=True),
    sa.Column('time', sa.String(length=40), nullable=True),
    sa.Column('preparation', sa.String(length=40), nullable=True),
    sa.Column('sms', sa.String(length=40), nullable=True),
    sa.Column('card_take', sa.String(length=40), nullable=True),
    sa.Column('branch', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=40), nullable=True),
    sa.Column('father', sa.String(length=40), nullable=True),
    sa.Column('unique_code', sa.String(length=40), nullable=True),
    sa.Column('secret', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('phone_extra', sa.String(length=40), nullable=True),
    sa.Column('mail', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order')
    op.drop_table('kampaniya')
    op.drop_index('id', table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ad', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('haqq', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('muddet', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('qaliq', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('valyuta', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('kredit', mysql.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('ad'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'cards', ['id'], unique=False)
    op.create_table('kampaniya',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('text', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bold', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('alt', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('soyad', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('ata', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('fin', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('mexfi', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('nomre', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('mail', mysql.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('card_user')
    # ### end Alembic commands ###
