"""Initial migration.

Revision ID: ace59cb8ed7b
Revises: 
Create Date: 2022-06-10 13:25:33.052097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace59cb8ed7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('haqq', sa.String(length=40), nullable=True),
    sa.Column('muddet', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('qaliq', sa.String(length=40), nullable=True),
    sa.Column('valyuta', sa.String(length=40), nullable=True),
    sa.Column('kredit', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('ad'),
    sa.UniqueConstraint('id')
    )
    op.create_table('kampaniya',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('bold', sa.String(length=200), nullable=True),
    sa.Column('alt', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('kampaniya')
    op.drop_table('cards')
    # ### end Alembic commands ###
